networks:
  pickside-network:
    external: true

services:
  msgsvc:
    build: .
    container_name: msgsvc
    ports:
      - "8083:8083"
    networks:
      - pickside-network
    environment:
      - VAULT_ADDRESS=${VAULT_ADDRESS}
      - VAULT_TOKEN=${VAULT_TOKEN}