networks:
  pickside-network:
    external: true

services:
  msgsvc:
    image: thenoobgrammer/pickside-service:message-service-latest
    container_name: msgservice
    ports:
      - "8083:8083"
    networks:
      - pickside-network
    environment:
      - VAULT_ADDRESS=https://vault.morpheglus.org
      - VAULT_TOKEN=${VAULT_TOKEN}